services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
    ports:
      - '5433:5432'
    networks:
      - sonarnet

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge