server:
  port:
    8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sonar
    username: sonar
    password: sonar
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  app:
  jwt-secret: whrjbfwhrfihrihfri
  jwt-expiration-ms: 100000