spring:
  application:
    name: eventBooking
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active : dev
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

server:
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
    min-response-size: 1024