server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sonar
    username: sonar
    password: sonar
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  app:
    jwt-secret: whrjbfwhrfihrihfri
    jwt-expiration-ms: 3600000

imagekit:
  public:
    api-key: public_LIgElrviVET2LIkcMOhQLrTaRcg=
  private:
    api-key: private_wq+dosqN31jAczCl9+N3AOsTN6o=
  imagekit:
    id: c4askreon
